/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as ClockRouteImport } from './routes/clock'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts/index'
import { Route as TrainingIndexRouteImport } from './routes/training/index'
import { Route as TrainingDetailsRouteImport } from './routes/training/details'
import { Route as WorkoutsImportCodeRouteImport } from './routes/workouts/import/[code]'

const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const ClockRoute = ClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingDetailsRoute = TrainingDetailsRouteImport.update({
  id: '/training/details',
  path: '/training/details',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsImportCodeRoute = WorkoutsImportCodeRouteImport.update({
  id: '/workouts/import/code',
  path: '/workouts/import/code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clock': typeof ClockRoute
  '/exercises': typeof ExercisesRoute
  '/history': typeof HistoryRoute
  '/overview': typeof OverviewRoute
  '/training/details': typeof TrainingDetailsRoute
  '/training': typeof TrainingIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/workouts/import/code': typeof WorkoutsImportCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clock': typeof ClockRoute
  '/exercises': typeof ExercisesRoute
  '/history': typeof HistoryRoute
  '/overview': typeof OverviewRoute
  '/training/details': typeof TrainingDetailsRoute
  '/training': typeof TrainingIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/workouts/import/code': typeof WorkoutsImportCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clock': typeof ClockRoute
  '/exercises': typeof ExercisesRoute
  '/history': typeof HistoryRoute
  '/overview': typeof OverviewRoute
  '/training/details': typeof TrainingDetailsRoute
  '/training/': typeof TrainingIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/workouts/import/code': typeof WorkoutsImportCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clock'
    | '/exercises'
    | '/history'
    | '/overview'
    | '/training/details'
    | '/training'
    | '/workouts'
    | '/workouts/import/code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clock'
    | '/exercises'
    | '/history'
    | '/overview'
    | '/training/details'
    | '/training'
    | '/workouts'
    | '/workouts/import/code'
  id:
    | '__root__'
    | '/'
    | '/clock'
    | '/exercises'
    | '/history'
    | '/overview'
    | '/training/details'
    | '/training/'
    | '/workouts/'
    | '/workouts/import/code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClockRoute: typeof ClockRoute
  ExercisesRoute: typeof ExercisesRoute
  HistoryRoute: typeof HistoryRoute
  OverviewRoute: typeof OverviewRoute
  TrainingDetailsRoute: typeof TrainingDetailsRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
  WorkoutsImportCodeRoute: typeof WorkoutsImportCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clock': {
      id: '/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof ClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/details': {
      id: '/training/details'
      path: '/training/details'
      fullPath: '/training/details'
      preLoaderRoute: typeof TrainingDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/import/code': {
      id: '/workouts/import/code'
      path: '/workouts/import/code'
      fullPath: '/workouts/import/code'
      preLoaderRoute: typeof WorkoutsImportCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClockRoute: ClockRoute,
  ExercisesRoute: ExercisesRoute,
  HistoryRoute: HistoryRoute,
  OverviewRoute: OverviewRoute,
  TrainingDetailsRoute: TrainingDetailsRoute,
  TrainingIndexRoute: TrainingIndexRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
  WorkoutsImportCodeRoute: WorkoutsImportCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
